pyxrf/gui.py, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/guessparam.py, pyxrf/view/fileio.enaml
These changes are the start of trying to keep a 1:1 model:view relationship.  Models should not need *too* many parameters from each other.  The ones that do need to be passed around should be done via the **Observer** pattern which can be seen in pyxrf/gui.py lines 119-121.
=> ENH: Start de-coupling models and views

pyxrf/model/fileio.py, pyxrf/view/fileio.enaml
Now using bluesky branch of hxntools, where the handler is separate from the detector class.
New hxntools loads full hdf5 spectra into memory if possible - 200x200 scans now load/save with `fio.make_hdf` in less than 3 minutes.
I've also updated the `li_ophyd_new` environment for the xf03id user to this new version.
=> MNT: import handlers from hxntools/bs branch

pyxrf/model/fit_spectrum.py
My name is Matthew Fraund and I'm a graduate student under Dr. Ryan Moffet from the University of the Pacific.  We've had a couple beamtimes at Juergen's XRF beamline and have been using your PyXRF fitting routine and GUI.
Trying to save the individual pixel fitting images to .tiff or .txt files would give the error: Directory name is incorrect "C:\\Users\\Matthew\\Working Directory\\output_txt_C:\\Users\\Matthew\\Working Directory"
I made a small change so that it would access the proper directory.
I'm brand new to python (and GitHub) and made these changes so that the two buttons would work but thought I may as well send the changes to you in case it helped.  The change made everything work as expected.
=> Fixing "save to .tiff" and "save to .txt" buttons

.gitignore, pyxrf/gui.py, pyxrf/model/fileio.py, pyxrf/view/fileio.enaml
The issue is fixed. Now Working Directory is set to the directory where input file is located. Once the input file is first opened, the button is disabled and Working Directory can not be changed manually, therefore the behavior of the program remains consistent (```working_directory``` and ```file_name``` track the location of the input file until the new file is selected). 
Two other changes:
-  File mask (*.h5) is added to the Open File dialog box, so that only .h5 files are displayed by default. '*' mask can also be selected if needed.
- MessageBox is added for reporting errors while reading data file. Before this change the program would crash if input file had incorrect format.
=> Fix: program crashes when opening a file not in Working Directory (issue 160)

pyxrf/model/guessparam.py, pyxrf/model/lineplot.py, pyxrf/model/param_data.py, pyxrf/view/fit.enaml
Improved consistency of two dialog boxes: Automatic Element Finding in Fit tab and Options in Spectrum View tab.  
Now the upper limit for element finding (E high [keV]) is automatically set 0.8 keV higher than incident E when incident E is changed. E high may be changed manually. The value of the incident energy in Options dialog box is kept in sync with E high. It still can be changed, but I don't think it is used anywhere.
=> Fill incident energy

pyxrf/model/draw_image.py, pyxrf/model/draw_image_rgb.py, pyxrf/model/fileio.py, pyxrf/model/lineplot.py, pyxrf/model/load_data_from_db.py, pyxrf/view/fileio.enaml
Fixed multiple issues related to data manipulation and presentation, including but not limited to
- loading and presentation of data from multichannel (3-channel) detectors;
- selection of individual detector channels or sum of all channels for further processing (fitting of elements);
- plotting data from different detector channel on the same plot for comparison;
- automatic scaling of the 'Spectrum View' plot (now works well in most situations, may be manually reset in the rest of cases);
- multiple issues in 'Element RGB' tab: enabled axes tick labels (no coordinates of x and y are printed in the toolbar along with values, not x= y= without values); fixed the issue with program crashing of less than 3 elements are selected for plotting; fixed mismatch between the order of scalers in …
=> Fix for multiple issues related to data manipulation and presentation

pyxrf/model/fileio.py, pyxrf/model/load_data_from_db.py
Fixed multiple issues related to loading of experimental data using Databroker. The main issues:
- Function ```make_hdf``` was not considering 3-channel data from Xpress3 detector as 1-channel data. When computing the sum of channels, only data from channel 1 was used. The fixed code correctly determines the number of channels in the input stream (using table dimensions) and uses complete data for calculations. Changes are only related to fly scan mode on the SRX beamline;
- Function ```make_hdf``` was crashing in attempt to load step-scan data from Databroker. The fixed code allows to load step-scan data from one or two Xpress 3 detectors. Code changes are only relevant for step scan data from SRX beamline.
Testing was performed on SRX WS4.
=> Loading multichannel detector data using Databroker

configs/srx_pv_config.json, pyxrf/model/load_data_from_db.py
The feature was requested by Andy K.
`make_hdf` may load from two detectors (`xs` - 3 channels and `xs2` - 1 channel) and create two separate files. It is assumed that data from detector `xs` can be accessed using the field `fluor` and the detector `xs2` using the field name `fluor_xs2`. The names of the field and associated detector names are now read from configuration file `/configs/srx_pv_config.json`. The detector names associated with field names are added to data file names to distinguish between files. It is also seems reasonable to recommend to permanently change experiment plans so that data from the detector `xs2` are always saved with field name 'fluor_xs2'
Additional changes to the configuration file `/configs/srx_pv_config.json`: field names for `xrf_detector` were changed …
=> New feature: `make_hdf` can load flyscan data from two detectors

pyxrf/model/draw_image.py, pyxrf/model/fit_spectrum.py
PyXRF was reported by to crash while plotting data for scan IDs 29929 and 29933. Two minor errors were corrected: rarely occurring division by 0 and plotting all-zeros image with imshow().
=> Fix: two cases of PyXRF crashing

MANIFEST.in
This PR fixes the issue with broken `.tar.gz` files being submitted to PyPI.
The dirs/files tree is as follows with this fix:
```
16:41 $ tree pyxrf-0.0.9.7+0.g7de7f75.dirty
pyxrf-0.0.9.7+0.g7de7f75.dirty
├── LICENSE
├── MANIFEST.in
├── PKG-INFO
├── README.md
├── configs
│   ├── hxn_pv_config.json
│   ├── pv_config.json
│   ├── srx_pv_config-original.json
│   ├── srx_pv_config.json
│   ├── xfm_pv_config.json
│   └── xrf_parameter.json
├── docs
│   ├── Makefile
│   ├── _static
│   │   ├── define_h5file.jpg
│   │   ├── define_h5file.pdf
│   │   ├── define_h5file.png
│   │   ├── load_parameter_file.png
│   │   ├── more_datasets.png
│   │   ├── select_data_plot.png
│   │   └── zoomin_plot.png
│   ├── conf.py
│   ├── credits.rst
│   ├── data_input.rst
│   ├── data_output.rst
│   ├── index.rst …
```
=> Fix source distribution for PyPI

pyxrf/model/draw_image.py, pyxrf/model/draw_image_rgb.py, pyxrf/view/image2D.enaml, pyxrf/view/rgb_image.enaml
The pull request includes two fixes (requested by @andrewmkiss:
- Image contrast adjustment in RGB data plot is functioning properly now: the presented range of values (min and max) is selected for each color (R, G and B) using sliders; the presented data is scaled so that values within the range fill the whole dynamic range of the RGB plot (the range int 0..255 is represented as float 0..1.0). The values that fall outside the range are moved to one of the dynamic range boundaries (set equal 0.0 or 1.0). This operation does not keep quantitative information, but allows to substantially improve the visual presentation of data if its values are in narrow range or the data contain visible background noise.
- A button 'Deselect All' is added to Image Selection tool in 2D Plot tab. The logic …
=> Fix: image contrast adjustment in RGB data plot

.travis.yml, docs-requirements.txt, pyxrf/model/draw_image.py, pyxrf/model/draw_image_rgb.py, pyxrf/model/load_data_from_db.py, requirements-docs.txt, requirements.txt, setup.py
Pull request fixes two problems:
- Program crashing while displaying .h5 file from incomplete experiment.
Generated HDF5 file from an experiment that was interrupted does not have 'positions' dataset. Attempt to plot data vs x,y coordinates crashes the program. Plotting functions (2D plot and RGB plot) were modified to prevent crashing. Modified functions disable all plotting and interpolation features that use x,y coordinates if 'positions' dataset is not available.
- Artificially generating x,y coordinates for 'positions' in case if the experiment is incomplete. 
This is addition to the first modification and represents more permanent fix for the problem. If the dataset is incomplete (which periodically happens on the beamlines), the `make_hdf` function generates missing values of x and …
=> Fix: crashing while working with data from incomplete experiment

configs/tes_pv_config.json, pyxrf/db_config/tes_db_config.py, pyxrf/gui.py, pyxrf/model/draw_image.py, pyxrf/model/guessparam.py, pyxrf/model/lineplot.py, pyxrf/model/load_data_from_db.py, pyxrf/view/fit.enaml, pyxrf/view/lineplot.enaml, requirements.txt
The update includes:
-- Additional buttons: `Remove` button in `Fit` tab;  `Add line` and `Remove line` buttons in `Spectrum View` tab.
-- Enabling/disabling of peak selection widgets depending on data availability. `Add` and `Remove` buttons are enabled/disabled depending on whether the line highlighted in the ComboBox is in the list of selected lines.
-- Coordination of behavior of line selection tools in `Fit` and `Spectrum View` tabs. Controls from either tab can be used to add and remove lines from the list.
-- Automatic estimation of peak intensity for peak that could be added (simplified estimation as difference between raw and interpolated data). The estimated peak intensity is displayed in the `Peak Int` field of the `Fit` tab. Estimated intensity can be manually changed before …
=> Feature: updated tools for manual selection of element excitation spectral lines

pyxrf/gui.py, pyxrf/model/command_tools.py, pyxrf/model/draw_image.py, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/guessparam.py, pyxrf/model/load_data_from_db.py, pyxrf/model/setting.py, pyxrf/view/fileio.enaml, pyxrf/view/fit.enaml, pyxrf/view/lineplot.enaml, pyxrf/view/main_window.enaml, pyxrf/view/setting.enaml
Implemented and fixed features include:
-- direct loading data from databroker by scan ID is working. Remotely tested on SRX, HXN and TES.
-- improved consistency of behavior of ``make_hdf`` and ``pyxrf_batch`` functions. Both functions will raise exception if error occurred during the processing if called for a single scan/file or go to processing the next scan/file if the list of files or range of scan IDs is provided. ``make_hdf`` will also may detect 'incomplete' scans that have no stop document.
-- fixed and improved functionality of ``ROI setting`` tab, which allows to compute ROIs. All features are operational and stable. Added an option to subtract background from raw data before computing ROIs.
-- fixed minor stability issues, including program crash when removing all selected …
=> Direct loading data from databroker. ROI settings tab.

pyxrf/gui.py, pyxrf/model/fit_spectrum.py, pyxrf/model/guessparam.py, pyxrf/model/lineplot.py, pyxrf/model/utils.py, pyxrf/view/fit.enaml, pyxrf/view/lineplot.enaml
Changes:
-- Better looking GUI tool for element line selection in ``Fit`` and ``Spectrum View`` tabs (combination of ``<``, ``>`` and element line selection ComboBox). Especially useful if PyXRF is used on MacOS.
-- Fixed program crash, which happens when element line is selected using ComboBoxes in ``Fit`` or ``Spectrum View`` tabs before initial fitting. Initial fitting is usually performed by running automated element search by clicking the ``Find Elements Automatically`` button in ``Fit`` tab. Now elements may be selected and element lines displayed in the ``Spectrum View`` tab before the initial fitting is done, but the elements may not be added to the list. If the ``Add`` button is pressed in ``Fit`` or ``Spectrum View`` tab befor the initial fitting is run, the Message Box offering …
=> GUI: tools for setting parameters of user defined peaks

pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/load_data_from_db.py, pyxrf/view/fileio.enaml
Changes:
-- The new optional keyword parameter ``file_existing_overwrite`` is added to the ``make_hdf`` function. If ``file_existing_overwrite`` is ``False`` and file for the scan ID already exists in the working directory, then `` make_hdf`` is raising exception if called for single scan ID or skips the scan if called for a range of scan IDs.  If ``file_existing_overwrite`` is ``True``, then the old file is overwritten with the new one. The overwrite option is disabled by default, because it may cause deletion of processing results. Note, that if the parameter ``fname_add_version`` is true, then new files with unique file names will be always created. (The feature was requested by SRX staff). 
- As a GUI extention of the new ``make_hdf`` feature, the ``Overwrite Existing Files`` checkbox …
=> Option to overwrite existing files (make_hdf and PyXRF GUI)

pyxrf/model/fileio.py, pyxrf/view/fit.enaml, pyxrf/view/image2D.enaml, pyxrf/view/lineplot.enaml, pyxrf/view/rgb_image.enaml
Two small changes:
-- ``Element Map`` tab -> Image Wizard: the range of displayed values may now be changed by moving sliders or by typing in the text fields. Sliders and text fields for each element line are now linked, so changes in one control are reflected in the state of the other control.
-- ``Fit`` tab -> Edit Element: set the window title. The ``Edit Element`` window was displayed with empty header, now it displays the title ``Edit Fitting Parameters for Selected Emission Lines``.
-- Removed unused ``Print`` button in 3 data plotting tabs. The button was crashing the program.
=> Fixes for three minor PyXRF GUI issues

.codecov.yml, .travis.yml, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/load_data_from_db.py, pyxrf/model/setting.py, pyxrf/simulation/sim_xrf_scan_data.py, pyxrf/view/fit.enaml
More efficient memory use by PyXRF:
-- Change the default options for loading data from databroker using GUI and 'make_hdf': only the sum of all channels are loaded from databroker and saved to local .h5 file.
-- Loading of all channels may be enabled by setting 'make_hdf' parameter 'create_each_det=True' or checking 'Load all channels' checkbox in GUI.
-- Raw spectral data for XRF maps are now stored in .h5 files and memory as np.float32 (instead of np.float64). The data is still converted to np.float64 before computations.
Additional minor change: the checkbox 'Overwrite existing file' in Dialog 'Save quantitative calibration' in the is unchecked after saving the file (as a safety feature, the checkbox must be checked each time the file needs to be overwritten).
=> Optimization of memory use

docs/installation.rst
Updated instructions for installation of PyXRF on user PCs. Scikit-beam should also be updated when the new version becomes available. Scikit-beam is not listed as dependency for PyXRF for smoother develop installation of the beamlines.
=> Updated installation instructions

pyxrf/core/quant_analysis.py, pyxrf/core/tests/test_quant_analysis.py, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/guessparam.py, pyxrf/view/fit.enaml
The following issues were fixed:
- GUI: data loaded from databroker using GUI controls was always saved to the current directory (from which PyXRF was started). In fixed version, data is saved to the working directory, selected in the dialog box opened using ``Working Directory`` button in ``File IO`` tab.
- GUI: fixed the issue with synchronization of the value of incident energy displayed in ``Automated Element Search`` window.
- GUI: fixed the issue with synchronization of calibration data preview and the ``distance-to-sample`` field in ``Save Quantitative Standard`` window.
- Changed computational code for quantitative calibration. Pixels along the edges of the map are likely to include outliers that visibly bias the computed calibration coefficients. In the changed code, all pixels …
=> Fixed multiple bugs

pyxrf/gui.py, pyxrf/model/fit_spectrum.py, pyxrf/model/guessparam.py, pyxrf/model/lineplot.py, pyxrf/view/fit.enaml
The changes in the PR:
- Display the range of selected energies on the spectrum plot (`Spectrum View` tab).
- A new option to interactively select initial location of user defined peaks. Initial amplitude of the user peak is estimated automatically using the same algorithm as for element emission lines.
- Fixed the bug that prevented normal operation of the program after attempt to add user defined peaks if upper bound on the selected range of energies is below 5.0 keV (needed for data produced by TES beamline).
- Fixed the bug that may have caused rare cases of deletion of emission lines from the list of selected lines.
=> ENH: improved management of user defined peaks

pyxrf/model/fit_spectrum.py, pyxrf/view/fit.enaml, pyxrf/xanes_maps/tests/test_xanes_maps_api.py, pyxrf/xanes_maps/xanes_maps_api.py
The following features were implemented:
-- Allow using any map (not only maps of element emission lines) for alignment of stacks of maps. For example, maps of total count (total scattering) may provide better performance for some experiments. Now the parameter ``emission_line_alignment`` of ``build_xanes_maps`` may be set to a valid emission line (e.g. ``"Fe_K"``) or to the name of any existing map (e.g. ``"total_cnt"``).
-- Normalization of a map stack used a alignment reference. Normalization can be turned on and off by setting ``normalize_alignment_stack`` parameter of ``build_xanes_maps``.
-- Button is added to interactive XANES map browsing window (``build_xanes_map``) to save average XANES spectrum based on the selected area of the map.
=> XANES mapping: using any existing map for stack alignment

pyxrf/xanes_maps/tests/test_xanes_maps_api.py
Some small corrections to tests for '_save_spectrum_as_csv' (see PR https://github.com/NSLS-II/PyXRF/pull/209). The updated tests check if the header with comments (`msg_info`) is successfully saved to file.
=> TST: corrected tests for '_save_spectrum_as_csv'

pyxrf/model/fit_spectrum.py
Small fix for the issue with multiprocessing on the latest MacOS. The only known solution at this point is to disable multiprocessing when the program is executed on the affected OS. The code changes implement the following steps:
- Check if the OS is MacOS.
- If MacOS is detected, then check if the version is 10.15 or higher.
- If the version is 10.15 or higher, then use `multiprocessing.pool.ThreadPool` instead of `multiprocessing.Pool` to execute computations. 
The solution should be considered temporary, since the performance is visibly reduced. But it makes PyXRF functional for the Mac users who recently updated OS. The change does not affect other users.
=> ENH: temporary fix for the issue with multiprocessing on MacOS

pyxrf/model/load_data_from_db.py
Data file naming scheme was changed following the request from SRX staff
=> Changed naming scheme for data files: no parentheses in the new file names

pyxrf/api.py, pyxrf/core/map_processing.py, pyxrf/core/tests/test_map_processing.py, pyxrf/model/command_tools.py, pyxrf/xanes_maps/xanes_maps_api.py
The default behavior of Dask is to create temporary directory `dask-worker-space` in the current working directory. The location of the temporary directory can be changed by configuring Dask. The desired location is `~/.dask`, which works on every OS if `~` is properly expanded.
The existing code was applying configuration after the client was created the first time in the application, so the temporary directories were still created. In the code for this PR, the order is changed so that Dask is always configured first, then the client is created. 
The tests were modified to verify that no temporary directory is created in the current directory.
=> Fixed the issue of Dask creating temporary directory in the current working directory.

pyxrf/api.py, pyxrf/api_dev.py
Create a separate file for importing exposed PyXRF APIs into custom script `pyxrf.api_dev`.
Now `from pyxrf.api import *` may be used to import PyXRF APIs into interactive IPython session and `from pyxrf.api_dev import *` when importing the APIs into a custom script. Now the difference between two files is limited to printing of the list of available functions when importing `pyxrf.api`, which is typically not needed when importing APIs into a script. In the future the files may include different sets of APIs.
=> Create separate file for importing APIs - 'pyxrf.api_dev'

pyxrf/gui_support/gpc_class.py, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py, pyxrf/model/lineplot.py, pyxrf/model/parameters.py, pyxrf/model/setting.py
In the original design of PyXRF, each module was keeping its own copy of fitting parameters and references to the raw and processed data. After refactoring, only a single copy of fitting parameters is maintained in `param_model` and each module that is using or modifying the parameters is keeping a reference to `param_model`. All references to raw and processed data were consolidated in `io_model`.
=> Consolidate storage and management of parameter and data.

.travis.yml, =1.20, pyxrf/gui_module/main_window.py, pyxrf/gui_module/tab_wd_plots_fitting_model.py, pyxrf/gui_support/gpc_class.py, requirements.txt
A number of changes for supporting updates of the spectrum plots  when parameters of energy axis are changed.
`pystackreg` was pinned to v2.2, since the newer version v2.5 requires numpy>=1.20. `pystackgreg` can be unpinned once Numpy v1.20 is available from `conda`.
OSX Python 3.7 unit test fails with error while building `numba`. The test is set as `allowed to fail`.
=> Improved support for variable energy axis parameters

pyxrf/db_config/hxn_db_config.py, pyxrf/db_config/srx_db_config.py, pyxrf/db_config/tes_db_config.py, pyxrf/db_config/xfm_db_config.py
Temporary fix that allows to avoid caching issues with `databroker>=1.0`: import `Broker` from `databroker.v0` instead of `databroker`.
=> Import 'Broker' from 'databroker.v0' if available

pyxrf/model/draw_image.py, pyxrf/model/lineplot.py, pyxrf/pyxrf_run.py, requirements.txt
The changes ensure that PyXRF will work once Matplotlib 3.4 is released. The changes include:
- Deprecated and removed `Colorbar.cbar_axis` is replaced by `Colorbar.ax.yaxis`.
- Plotting code is changed to ensure that subplot is created only once.
PyXRF will still segfault if used with Matplotlib 3.3, so Matplotlib 3.3.* is disabled in `requirements.txt`.
Special thanks to @tacaswell for help with solving the issues.
=> FIX: compatibility with Matplotlib 3.4

pyxrf/model/load_data_from_db.py
Explicit clearing of the cache was disabled if Data Broker v1.0.0 or above was installed. It led to incorrect behavior, if 'old' Data Broker  `databroker.v0` was used. Changes in this PR restore the correct functionality by verifying if attribute `handler_cache` exists (`hasattr(db.fs, "_handler_cache")`) and explicitly clearing the cache if it does.
The changes will be checked at the beamline before the PR is merged.
=> Clearing the cache in case of 'databroker.v0'

.travis.yml, requirements.txt
Unpinned `pystackreg`. Removed OSX Python 3.6 tests from CI. Added tests with Python 3.8 and Python 3.9 for OSX.
=> CI: Unpinned `pystackreg`.

pyxrf/model/fit_spectrum.py
The heights (areas) of emission lines are initialized with a reasonable value (1000) each time before the first step of fitting of total spectrum. Initialization slightly improves fitting time and prevents rare occurrances of very long conversion time on some datasets in cases the parameters are very close to optimal values and areas of some peaks are very small. This change does not prevent the issue to occur in case the 2nd step of optimization is enabled, but the 2nd step is disabled by default and seems to be very rarely used.
=> Improved stability of fitting algorithm for total spectrum fitting

pyxrf/__init__.py, pyxrf/api_dev.py, pyxrf/model/load_data_from_db.py, pyxrf/model/tests/test_hdf5_file_operations.py
Some minor improvements in `save_data_to_hdf5` and `read_data_from_hdf5` functions for more consistency and better treatment of metadata. The functions now must be imported from `pyxrf.api` or `pyxrf.api_dev`, which is consistent with the other function.
=> Improvements in functionality of 'save_data_to_hdf5' and 'read_data_from_hdf5'

pyxrf/model/load_data_from_db.py
Fix the issue with loading corrupt data at TES beamline. The dataset contained one row with smaller number of data points (420 instead of 900). The corrupt row occurred due to acquisition being suspended after beam dump and then resumed.
=> Fix issue with loading corrupt files at TES

pyxrf/model/load_data_from_db.py
Minor changes to TES-specific code that allows to load data from scans that were stopped. Only map rows that were scanned are loaded.
=> TES: load data from incomplete

.github/workflows/docs_publish.yml
Changed external repository name from `PyXRF/nsls-ii.github.io` to `nsls-ii/nsls-ii.github.io`. This may fix the issue of publishing documentation.
=> Fixed 'external_repository' name for Doc publishing

docs/Makefile, docs/make.bat
Change the directory for building the docs to standard `/docs/build/html`. This is expected to fix doc publishing.
=> Change directory for doc building to a standard 'build'

.github/workflows/docs_publish.yml
Changed 'external_repository' name in deployment script from `nsls-ii/nsls-ii.github.io` to `NSLS-II/NSLS-II.github.io`.
=> Changed 'external_repository' name in deployment script

pyxrf/core/map_processing.py, pyxrf/model/command_tools.py, requirements.txt
This PR contain changes that are necessary for PyXRF to work with `distributed` >= 2019.7.0. No officially supported method to clear Dask cache was found, but Dask tends to release resources and close open files if it is fed with additional small `dummy` task. HDF5 file needs to be opened with `mode='r'` to work with Dask arrays and it needs to be closed before it could be opened with `mode='a'` for writing the result.
=> Fix for the issue of compatibility with Dask `distributed` >= 2019.7.0

pyxrf/model/load_data_from_db.py, pyxrf/model/scan_metadata.py
Changes:
- Add new metadata entries to HDF5 files for SRX fly scans: `param_interferometer_posX`, `param_interferometer_posY`, `param_interferometer_posZ` and `instrument_beam_current`.
- Implement capability to load corrupt data with some data rows having the number of points less than expected (e.g. scan #102003).
=> Add new metadata to HDF5 file (SRX)

pyxrf/core/map_processing.py
Change the location of Dask cache when PyXRF is running on Linux. The cache is now located in `/tmp/<user_name>/dask` directory. It is still located in `<user_home_dir>/.dask` directory if PyXRF is running on Windows or OSX. The change is expected to fix issues that occur on beamline workstations, where user home directories are on slow NFS.
=> Place Dask cache into /tmp directory on Linux

pyxrf/model/load_data_from_db.py
Modified the code for loading SRX scans with 'new' metadata to load corrupt scans. The loading function tries to 'repair' data by detecting and replacing incomplete rows in all tables, including fluorescence data, scalers and positions. This is an extension of the PR https://github.com/NSLS-II/PyXRF/pull/258
=> Extend capabilities of load corrupt scans at SRX beamline

pyxrf/api_dev.py, pyxrf/gui_support/gpc_class.py
A new function `autofind_emission_lines`. The function loads specified .h5 file, automatically searches for the emission lines and generates .json file with fitting parameters. 
Example:
```
from pyxrf.api import autofind_emission_lines
autofind_emission_lines("scan2D_101042_xs_sum4ch.h5", "parameters.json")
```
=> New API: 'autofind_emission_lines'

pyxrf/model/load_data_from_db.py
nano_stage_top stages are not found in stream0 so make_hdf will fail. I added a check to grab these values from the primary stream.
=> Fixed make_hdf to include stepping with top stages

pyxrf/model/command_tools.py
Removed distance_to_sample=quant_distance_to_sample from the definition "fit_pixel_data_and_save" call to "output_data" when save_txt == True. This fixes the bug that gives the error "TypeError: output_data() got an unexpected keyword argument 'distance_to_sample'"
=> Remove TypeError from fit_pixel_data_and_save when save_txt == True

pyxrf/gui_module/tab_wd_plots_fitting_model.py, pyxrf/gui_support/gpc_class.py, pyxrf/model/lineplot.py
The changes prevent line plots (total spectrum and fitting) from being hidden during computation. The old spectrum remains displayed until the new spectrum is ready, so that the change of the plot is instant and it is easier for the operator to observe changes in fitting.
- Line plots are no longer hidden during computations.
=> Do not hide line plots (total spectrum and fitting) during computation

pyxrf/gui_module/wnd_detailed_fitting_params.py, pyxrf/gui_module/wnd_image_wizard.py, pyxrf/gui_support/gpc_class.py
The PR includes implementation of the following requested GUI features:
- `Add All Elements` button is added to Image Wizard. The button adds all element emission lines to the selection. Issue: https://github.com/NSLS-II/PyXRF/issues/281.
- Absolute energy values are displayed for `Userpeak.._delta_center` parameter in the window 'Fitting Parameters for Individual Emission Lines'. Issue: https://github.com/NSLS-II/PyXRF/issues/282. 
- 'Auto' checkbox is added to the windows 'Fitting Parameters for Individual Emission Lines' and 'Shared Detailed Fitting Parameters'. Issue: https://github.com/NSLS-II/PyXRF/issues/283
- New button `Add All Elements` is added to Image Wizard. The button adds all element emission lines to the selection. 
-  'Auto' checkbox is added to the windows 'Fitting …
=> Requested GUI features

pyxrf/model/load_data_from_db.py
Changes to the code, which loads SRX experimental data from Databroker.
Positions of course stages are not captured during flyscans and need to be generated when the data is loaded from Data Broker and saved as HDF5 files. The positions are generated based on input scan parameters from the start document. Positions are generated for the following motors: 
```
"nano_stage_x", "nano_stage_y", "nano_stage_z", "nano_stage_topx", "nano_stage_topz"
```
The motors could be used for fast axis, slow axis and both. The axes are treated independently.
The generated positions are saved to HDF5 file. The HDF5 files can be handled as usual.
- SRX beamline: The positions for course stages are now generated based on plan input parameters. The following motors are supported: `nano_stage_x`, …
=> Generate position data for course stages (SRX).

.github/workflows/testing.yml, pyxrf/model/load_data_from_db.py
Support for `Fly1D`, `dmesh` and `dscan` used at HXN. Now data from those scans can be loaded using `make_hdf`. Additional parameter `fail_for_plan_types` is added to `make_hdf`, which accepts a list of plan types to ignore.
- `make_hdf` now supports `Fly1D`, `dmesh` and `dscan` (HXN).
- New parameter `fail_for_plan_types` is added `make_hdf`. The parameter accepts a list of plan types ignored by `make_hdf` (`make_hdf` is raising an exception when loading a single plan).
=> Support for Fly1D, dmesh and dscan (HXN)

.flake8, pyxrf/model/load_data_from_db.py
The changes allow loading data with corrupt rows (e.g. missing or corrupt data file). If the corrupt row is in the middle of the scan, it is replaced by the average of the previous and the next row.
- Loading data with corrupt rows in the middle of the scan (TES).
=> ENH: reading data with corrupt row(s) (TES)

pyxrf/model/load_data_from_db.py
Fix for compatibility with 2023-1.0 environment. When loading the step scan data, PyXRF recognizes Xspress3 channel names, where channel number is represented using two digits (`xs_channel01`, `xs_channel02` etc. instead of `xs_channel1`, `xs_channel2` etc.). The old channel names are also recognized.
- Fixed the code for loading step scan data at SRX. PyXRF can now load the step scan data recorded using 2023-1.0 environment.
=> SRX: extended the set of supported channel names (step scan)

pyxrf/core/quant_analysis.py, pyxrf/core/tests/test_xrf_utils.py, pyxrf/core/xrf_utils.py, pyxrf/gui_module/dlg_export_to_tiff_and_txt.py, pyxrf/gui_module/main_window.py, pyxrf/gui_module/tab_wd_fit_maps.py, pyxrf/gui_module/tab_wd_plots_rgb_maps.py, pyxrf/gui_module/tab_wd_plots_xrf_maps.py, pyxrf/gui_support/gpc_class.py, pyxrf/model/command_tools.py, pyxrf/model/draw_image.py, pyxrf/model/draw_image_rgb.py, pyxrf/model/fileio.py, pyxrf/model/fit_spectrum.py
Changes in this PR extend functionality of quantitative analysis features. Previously, quantitative normalization of maps could be applied only to the emission lines with existing calibration. This functionality is still used as default when quantitative analysis  is enabled (`Quantitative` checkbox is checked in `XRF maps` and `RGB` tabs or in `Export to TIFF and TXT ...` dialog box). A new combo box (to the right of `Quantitative` checkbox) allows to select reference emission lines from the list of emission lines with existing calibration. The list is populated after calibration data is loaded using `Load Quantitative Calibration`. Once the reference line is selected, the adjusted quantitative calibration for the reference line is used to normalize the maps for the rest of the emission …
=> Extended Quantitative Analysis

docs/source/installation.rst, pyxrf/model/lineplot.py
Matplotlib 3.7.0 does not support `remove` method of `ArtistList` class. The code was modified to call `remove()` methods of artists directly.
- PyXRF is now compatible with Matplotlib 3.7.0.
=> Compatibility with MPL 3.7.0

configs/hxn_pv_config.json
PyXRF used to load 8 scaler channels from Databroker. The number of channels was increased to 12.
- Load 12 scaler channels from Databroker (HXN beamline).
=> HXN: load 12 scaler channels from Databroker

pyxrf/core/xrf_quant_standards.yaml
The concentrations of elements for AXO standard were incorrectly converted from ng/mm^2 to ug/cm^2. This PR fixes the numbers.
=> Fixed concentrations for AXO quantitative calibration standards

.github/workflows/testing.yml, docs/source/installation.rst
Installation using `conda` from `conda-forge` currently does not work properly on Windows (requires additional tweaking). Use `mamba` for installation of PyXRF.
=> Updated installation instructions (for Windows)

.github/workflows/black.yml, .github/workflows/flake8.yml, pyxrf/model/fit_spectrum.py
The first column of the `.txt` file now is energy in kEv.
=> Fix formatting of 'txt' file saved by 'Save Spectrum/Fit'

pyxrf/model/draw_image.py, pyxrf/model/draw_image_rgb.py, pyxrf/model/fit_spectrum.py
Fixed multiple minor bugs:
- Fixed 'Save spectra for pixels in selected region' ('Maps' tab).
- Selection of axes scale (Pixels vs. Positions) is not reset after each fitting of the map.
Resolves issue https://github.com/NSLS-II/PyXRF/issues/316
- Fixed 'Save spectra for pixels in selected region' ('Maps' tab).
- Selection of axes scale (Pixels vs. Positions) is not reset after each fitting of the map.
Changes are tested manually.
=> Fix multiple bugs

pyxrf/model/lineplot.py, pyxrf/model/load_data_from_db.py
Loading of experimental data from the Tiled server for SRX beamline. Data is loaded and saved to HDF5 file in blocks of ~40,000 pixels and allows to load large maps without excessive memory use. The procedure is efficient for loading and saving the sum of all data. It also works for loading individual channels, but is very slow.
Replaced deprecated `BrokenBarHCollection` with `PolyCollection`. PyXRF is now compatible with Matplotlib 3.9.0.
Data collected during 2D step scans still can not be loaded using Tiled.
- Compatibility with Matplotlib 3.9.0: deprecated `BrokenBarHCollection` was replaced with `PolyCollection`.
- Optimized data loaded from Tiled server for SRX beamline.
=> 'Lazy' loading of Dask arrays from Tiled (SRX)

pyxrf/gui_module/dlg_edit_user_peak_parameters.py, pyxrf/gui_module/dlg_find_elements.py, pyxrf/gui_module/dlg_pileup_peak_parameters.py, pyxrf/gui_module/dlg_save_calibration.py, pyxrf/gui_module/tests/test_useful_widgets.py, pyxrf/gui_module/useful_widgets.py, pyxrf/gui_module/wnd_load_quant_calibration.py, pyxrf/gui_module/wnd_manage_emission_lines.py, pyxrf/model/lineplot.py
`QDoubleValidator` is set to always use US locale
- Issue with failing validation of floating point values using QDoubleValidator in non-US (DE) locale.
=> Fix the issue with validation of with QDoubleValidator in non-US (DE) locale

pyxrf/model/load_data_from_db.py
Support for loading data from Tiled at TES beamline
- Support for loading data from Tiled at TES beamline.
=> Support for reading from Tiled at TES

pyxrf/model/load_data_from_db.py
=> FIX: fix incorrect number of rows in incomplete scans (SRX)

pyxrf/gui_module/main_window.py, pyxrf/model/load_data_from_db.py
Fixed the issue with loading raw data collected at SRX. If a step scan is interrupted in the row, the collected data needs to be padded with extra data points (zeros) to fill the last scanned row. The changes in this PR implement this procedure.
- Data loading function for SRX beamline. Fixed the issue that prevented loading of incomplete step scans.
The modified PyXRF were manually tested at the beamline on the following: scan IDs 163746 (interrupted step scan) and 163747 (complete step scan).
=> Fixed data loading code for SRX: step scan data failed to load if the scan is incomplete

pyxrf/core/map_processing.py, pyxrf/model/lineplot.py
Resolved two compatibility issues: 
- with Numba v0.61.0;
- with Matplotlib 3.10
- Resolved compatibility issue with Numba 0.61.0.
- Resolved compatibility issue with Matplotlib 3.10
Manually tested.
=> Resolved multiple issues with PyXRF
