NSLS2/PyXRF

pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/guessparam.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml
pyxrf/view/guessparam.enaml

Also fitting results are added to the GUI.

Plotting is consistent for guess_param and fit 

---

pyxrf/model/fileio.py
pyxrf/view/fileio.enaml

Pickle file

---

README.md
pyxrf/model/draw_image.py
pyxrf/model/draw_image_rgb.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/lineplot.py
pyxrf/model/setting.py
pyxrf/view/fit.enaml
pyxrf/view/image2D.enaml
pyxrf/view/lineplot.enaml
pyxrf/view/main_window.enaml
pyxrf/view/rgb_image.enaml
pyxrf/view/setting.enaml

DEV: change r+ as r, and find bugs in app.processEvents

---

README.md
pyxrf/model/draw_image.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/lineplot.py
pyxrf/model/setting.py
pyxrf/view/fit.enaml
pyxrf/view/main_window.enaml
pyxrf/view/setting.enaml

DEV: save tiff and txt

---

conda-recipe/meta.yaml
pyxrf/model/fit_spectrum.py
pyxrf/model/guessparam.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml

Bugs fixed on pileup peak

---

pyxrf/model/fit_spectrum.py

DEV: fit with bg change

---

README.md
conda-recipe/meta.yaml

Fixed issues on installation in linux.

DOC: easy installation

---

pyxrf/model/fit_spectrum.py
pyxrf/view/fit.enaml

And fixed bugs when saving files.

Undo function

---

conda-recipe/meta.yaml
examples/Batch_mode_fit.ipynb
examples/make_hdf_stitched_function.ipynb
pyxrf/model/fit_spectrum.py

More doc and tutorials to be added. 

---

conda-recipe/meta.yaml
configs/hxn_pv_config.json
pyxrf/model/draw_image.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/guessparam.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml
pyxrf/view/main_window.enaml

more doc is required, and unit change on cs is updated.

WIP: Doc and unit change

---

.ipynb_checkpoints/Untitled-checkpoint.ipynb
Untitled.ipynb
examples/.ipynb_checkpoints/summed_spectrum_fit-checkpoint.ipynb
examples/summed_spectrum_fit.ipynb
pyxrf/api.py
pyxrf/model/draw_image.py
pyxrf/model/fileio.py
pyxrf/view/image2D.enaml

Add scatter plot and fix position issues, per @imrealkaren request. 
Still in process.

Dataio srx

---

README.md
examples/Batch_mode_fit_for_APS-2IDE-Bionanoprobe_data.ipynb
pyxrf/api.py
pyxrf/gui.py
pyxrf/model/command_tools.py
pyxrf/model/draw_image.py
pyxrf/model/draw_image_rgb.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml
pyxrf/view/image2D.enaml
pyxrf/view/lineplot.enaml

This is still in process, and should be done soon.

update in plotting and bug fix

---

pyxrf/model/fileio.py

For fly scan at srx. in process

DEV: hdf for srx

---

pyxrf/model/fileio.py

still need to add positions information.

make_hdf with flyscan for srx

---

pyxrf/model/fileio.py

This is like a temporary solution at pyxrf fileio for hxn.

DEV: two databses at hxn

---

pyxrf/model/fileio.py

Change made at SRX
@awalter-bnl

Added a beamline ID = SRX to an if statement

---

pyxrf/db_config/hxn_db_config.py
pyxrf/model/command_tools.py
pyxrf/model/fileio.py

Before 2019 c1.0

---

pyxrf/db_config/srx_db_config.py

DEV: dexela detector added

---

pyxrf/api.py
pyxrf/db_config/hxn_db_config.py
pyxrf/gui.py
pyxrf/model/data_to_analysis_store.py
pyxrf/model/fit_spectrum.py
pyxrf/model/load_data_from_db.py
pyxrf/view/fit.enaml

This is a simple case of analysis store to save fitting results directly. We assume data fitting is already done, and results are saved as dict of 2D images. 
This is different from streaming mode which works on document one by one.

Analysis store

---

pyxrf/model/draw_image.py
pyxrf/view/fileio.enaml
pyxrf/view/image2D.enaml

- Removed 'Plot Experiments (Do not use, to be deprecated)' push button from FileIO tab (the button used to crash the program)
- Fixed normalization issue of 2D plotted data (issue #157).
- Fixed inconsistencies in formatting of 2D data plots.

Normalization of 2D plotted data and a few other issues

---

pyxrf/gui.py
pyxrf/model/draw_image.py
pyxrf/model/draw_image_rgb.py
pyxrf/model/fit_spectrum.py
pyxrf/model/guessparam.py
pyxrf/model/lineplot.py
pyxrf/model/load_data_from_db.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml
pyxrf/view/lineplot.enaml

Fixed issues of compatibility with lmfit 0.9.13. The changes support respective pull request for ```scikit-beam```: https://github.com/scikit-beam/scikit-beam/pull/547.
Additional changes: fixed issue with undefined variable ```calculation_info``` in ```save2Dmap_to_hdf``` function.

Compatibility with lmfit 0.9.13

---

LICENSE
pyxrf/__init__.py
pyxrf/gui.py
pyxrf/model/draw_image.py
pyxrf/model/draw_image_rgb.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/guessparam.py
pyxrf/model/lineplot.py
pyxrf/model/load_data_from_db.py
pyxrf/model/param_data.py
pyxrf/model/setting.py
pyxrf/model/utils.py
pyxrf/view/fileio.enaml
pyxrf/view/fit.enaml
pyxrf/view/guessparam.enaml
pyxrf/view/image2D.enaml
pyxrf/view/lineplot.enaml
pyxrf/view/main_window.enaml
pyxrf/view/rgb_image.enaml
pyxrf/view/setting.enaml

A number of issues was fixed, particulary:
- Variable range for the Color Bar in the `scatter` plot (the range may not be set by `clim` parameter as in `imshow`): 
a. the range is controlled by using sliders in the image wizard; 
b. a nicely looking colorbar is displayed for data that consists of identical data points. 
- Fixed intermittent crashing issue during spectrum fitting on summed data.
- Started separating functions that will eventually be moved to `scikit-beam`.

Fix for a number of data visualization issues

---

pyxrf/gui.py
pyxrf/model/draw_image.py
pyxrf/model/draw_image_rgb.py
pyxrf/model/fileio.py
pyxrf/view/image2D.enaml
pyxrf/view/rgb_image.enaml

The features implemented in this PR:
- Automated check for the new version of PyXRF at nsls2forge. The message about new version availability and the new version number is displayed as part of the Main Window title.
- Implemented grid interpolation for RGB plot.

Grid fitting for RGB plot. Check for the latest version.

---

setup.py

Here is a PR to clean up the `setup.py` file.

CLN: clean up setup.py

---

.gitignore
pyxrf/api.py
pyxrf/model/command_tools.py
pyxrf/model/load_data_from_db.py
pyxrf/view/fileio.enaml

This PR involves the following changes to the code:
-- Refactoring of ``pyxrf_batch`` function (may be called from IPython or from custom scripts).
-- Testing PyXRF on data from HXN beamline.
-- Validation of batch processing routines (``make_hdf`` and ``pyxrf_batch`` on data from HXN and SRX beamlines.

Batch processing. Validation of HXN support.

---

pyxrf/api.py
pyxrf/gui.py
pyxrf/model/command_tools.py
pyxrf/model/fileio.py
pyxrf/model/fit_spectrum.py
pyxrf/model/lineplot.py
pyxrf/model/load_data_from_db.py
pyxrf/model/utils.py
pyxrf/model/xrf_energy.py
pyxrf/view/fit.enaml
pyxrf/xanes_maps/__init__.py
pyxrf/xanes_maps/xanes_maps_api.py
requirements.txt

Implementation of XANES workflow for imaging beamlines. The workflow may be called using two functions:
-- function ``build_xanes_map_api`` executes workflow that incudes: (a) loading data from databroker (uses ``make_hdf``, the step can be disabled) (b) runs processing of the set .h5 files (uses ``pyxrf_batch``, the step may be disabled); (c) computes XANES maps based on the stack of XRF maps from the set of .h5 files; (d) provides options to control every step of data processing.
-- function ``build_xanes_map`` is a wrapper for ``build_xanes_map_api`` that catches exceptions and prints error messages.

XANES imaging workflow

---

setup.py

Added ``pyxrf.xanes_maps`` package to ``setup.py``

Added 'pyxrf.xanes_maps' package

---

setup.py

Fix for installation issue: missing YAML file with QA reference standards.

Include YAML data file in the package

---

MANIFEST.in

Change to MANIFEST.in: include YAML files in the package.

Another fix for problem with packaging

---

pyxrf/core/xrf_utils.py

Changes to make PyXRF compatible with xraylib 3.0 and 4.0.

Compatibility with xraylib 4

---

pyxrf/xanes_maps/xanes_maps_api.py

Issue: incorrect parameter was used while calling `pyxrf-batch`.

ENH: fixed minor bug in XANES fitting module

---

pyxrf/core/quant_analysis.py
pyxrf/core/tests/test_fitting.py
pyxrf/core/tests/test_map_processing.py
pyxrf/core/tests/test_quant_analysis.py
pyxrf/core/xrf_utils.py
pyxrf/model/command_tools.py
pyxrf/model/fileio.py
pyxrf/model/lineplot.py
pyxrf/model/load_data_from_db.py
pyxrf/simulation/tests/test_sim_xrf_scan_data.py
pyxrf/xanes_maps/xanes_maps_api.py

A number of trivial changes to comply with style requirements of `flake8` v3.8.1

Compliance with updated version of `flake8`

---

pyxrf/core/map_processing.py
pyxrf/core/tests/test_map_processing.py

Issue reported by SRX. PyXRF crashed when loading an unchunked HDF5 file.

Minor fix: crash while loading of unchunked HDF5 files.

---

pyxrf/gui_module/main_window.py
pyxrf/gui_support/gpc_class.py

FIX: update element cross-section values when the incident energy is changed

---

.travis.yml
=1.20
pyxrf/gui_module/tests/test_useful_widgets.py
pyxrf/model/fileio.py

Minor changes to make the code compatible with newer package versions: h5py>=3.0 and pyqt>=5.12

Compatibility with h5py>=3.0 and pyqt>=5.12

---

docs/installation.rst
requirements.txt

Updated installation instructions: options to install from `conda-forge` or `nsls2forge`.

DOC: installation instructions

---

pyxrf/model/load_data_from_db.py

Fix for the issue of program crashing while loading data at TES.

Fix: crashing while loading data from Databroker at TES

---

.github/workflows/flake8.yml

The main purpose for this PR is to activate CI using GH actions. A simple GH action that runs style check using `flake8` is copied from a different project.

CI: enable GH actions

---

pyxrf/__init__.py
pyxrf/model/command_tools.py
pyxrf/model/fileio.py
pyxrf/model/load_data_from_db.py
pyxrf/model/scan_metadata.py
pyxrf/model/tests/test_hdf5_file_operations.py
pyxrf/simulation/sim_xrf_scan_data.py

Refactored the code to implement functions for reading and writing raw XRF data in HDF5 file. The functions do not read/write processed data (XRF maps).
```
from pyxrf import save_data_to_hdf5, read_data_from_hdf5
```

Functions for reading and writing raw data

---

pyxrf/model/load_data_from_db.py

Minor fix for handling of file names while loading XFM data from Data Broker to PyXRF GUI.

Fix file name handling during XFM data handling

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
docs/work_at_beamlines.rst
pyxrf/model/load_data_from_db.py
requirements-docs.txt

Changes:
- Small fix that allows loading data from scans that use both `xs` and `xs2` (new SRX format). 
- Fixed documentation compatibility with the new Sphinx. Unpinned Sphinx.
- Added PR and issue templates.

Load and save data from both 'xs' and 'xs2' (SRX)

---

pyxrf/model/load_data_from_db.py

Add detector 'xs4' to data loading function for SRX

Add detector 'xs4' to data loading function for SRX

---

.github/workflows/testing.yml
pyxrf/model/load_data_from_db.py

Clear cache after loading each run. Cache was cleared in the code using Databroker v0. The PR extends it to Databroker v1.

Clear cache after loading each run (Databroker v1)

---

.github/workflows/testing.yml
docs/source/installation.rst
pyxrf/gui_module/dlg_select_quant_standard.py
pyxrf/gui_module/wnd_compute_roi_maps.py
pyxrf/gui_module/wnd_detailed_fitting_params.py
pyxrf/gui_module/wnd_image_wizard.py
pyxrf/gui_module/wnd_load_quant_calibration.py
pyxrf/gui_module/wnd_manage_emission_lines.py

Update installation instructions. Extended unit tests to include Python 3.10. The PR does not change any functionality of the application or API.

Update installation instructions

---

pyxrf/model/load_data_from_db.py
requirements.txt

Update procedure for loading raw data at SRX beamline using intake version of Databroker v1. The updated procedure is loading and consecutively filling individual documents and allows to load large data files without using excessive system resources.
- Improved procedure for loading raw data at SRX beamline using Databroker V1.

Large files

---

pyxrf/model/load_data_from_db.py

Modification of the function for loading of raw data from Databroker for SRX. The modified code fix data with corrupt rows by replacing those rows with data from the closest valid row.

Loading of raw data: correction of corrupt rows (SRX)

---

pyxrf/gui_support/gpc_class.py
pyxrf/model/fileio.py
pyxrf/model/load_data_from_db.py
pyxrf/xanes_maps/xanes_maps_api.py

Additional improvement in handling data from multiple scan types. This PR is continuation of https://github.com/NSLS-II/PyXRF/pull/291

Proper handling of dscan (HXN)

---

docs/source/release-notes.rst

Release notes: v1.0.21

---

docs/source/conf.py
docs/source/installation.rst

Include a note with additional instructions for Windows users.

Updated installation instructions (for Windows users)

---

.github/workflows/testing.yml
pyxrf/core/map_processing.py
pyxrf/db_config/tes_db_config.py

Changes:
- Support for loading data generated by updated Bluesky plans (Community Xspress3 IOC).
- Compatibility with Dask/Distributed v2023.04.x.
- Compatibility with Dask/Distributed v2023.04.x.
- Support for loading data generated by updated Bluesky plans (Community Xspress3 IOC).

New XSP3 IOC at TES beamline

---

pyxrf/core/xrf_quant_standards.yaml

Add AXO C1 and C10 quantitative calibration standards to the .yml file.
- Quantitative calibration standards AXO C1 and C10 were added.

ENH: add AXO C1 and C10 standards

---

pyxrf/model/catalog_management.py
pyxrf/model/load_data_from_db.py

Minor improvements in the code for lazy data loading from Tiled.

ENH: minor improvements in data loading from Tiled

---

.github/workflows/testing.yml
pyxrf/model/lineplot.py

- Replaced call to deprecated `remove` method of ArtistList with `remove` method of the artist.

Fix for the deprecated 'remove' method of ArtistList

---

pyxrf/model/draw_image.py
pyxrf/model/lineplot.py
pyxrf/model/load_data_from_db.py

Fixed the code for loading step scan data from Tiled (SRX beamline.
- Fixed code for loading step scan data from Tiled (SRX beamline).

ENH: working code for loading step scan data from Tiled (SRX)

---

pyxrf/db_config/xfm_db_config.py

Data can not be loaded using Databroker V0 any more. Switch to Databroker V1.
- Update data loading code for XFM

Fix for data loading at XFM

---

pyxrf/db_config/xfm_db_config.py
pyxrf/model/load_data_from_db.py

Fixed loading data for fly scans at SRX (after Tiled server update).

FIX: fix data shape for scaler (SRX)
